import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import SocketProvider from '@/providers/SocketProvider'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const theme = {
    baseTheme: dark,
    layout: {
        logoPlacement: 'inside',
        socialButtonsPlacement: 'bottom',
        socialButtonsVariant: 'iconButton',
        showOptionalFields: true,
        helpPageUrl: 'https://clerk.dev/support',
        privacyPageUrl: 'https://clerk.dev/privacy',
        termsPageUrl: 'https://clerk.dev/terms',
    },
    elements: {
        // formButtonPrimary: 'bg-purple-800',
        // footerActionLink: 'text-purple-800',
    },
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

// clerk provider wraps HTML move it back

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' className='h-full'>
            {/* <ClerkProvider appearance={theme}> */}
            <body className={`${inter.className} h-full bg-zinc-900 text-zinc-100`}>
                <SocketProvider>{children}</SocketProvider>
            </body>
            {/* </ClerkProvider> */}
        </html>
    )
}
